### ISSUE TITLE
Add option to treat "false" as the required value to remove code

### ISSUE THREAD

**Issue by JacobDB** [crissdev/gulp-remove-code#12]
I think in a lot of cases it would be nice to be able to say "remove if false," rather than "remove if true." This is mostly just for naming purposes.

For example, let's say we're trying to remove a block of code that should only show up on a if the page is responsive. Currently, we'd need to set something like the following to remove the responsive code:

    
    ...
    

It'd be a bit less awkward to say something like:

    
    ...
    

Minor quibble, I just think the way some situations need to be worded (like the above) could be confusing.

**Comment by JacobDB** [comment]
I suppose this could be accomplished using the "commentEnd" template, like so:

    .pipe(plugins.remove_code({login_html: plugins.argv.remove && plugins.argv.remove.includes("login") ? true : false, commentStart: ""}))

as such, I'll close this issue.

**Comment by crissdev** [comment]
@JacobDB **chrilith** implemented it in this commit https://github.com/crissdev/gulp-remove-code/commit/bba3915b4700a578790256b20aca0126212f6537. See #14
