### ISSUE TITLE
Error Handling Anti-Pattern

### ISSUE THREAD

**Issue by CodeMan99** [crissdev/gulp-remove-code#15]
I see that you are actively refactoring for various reasons. You should consider changing the error handling as well. In a few places you have something like the following.

```javascript
try {
   if (err) {
      return callback(err);
   }
   // more stuff
} catch (e) {
   callback(e);
}
```

The usage of the callback inside of your try-catch is bad, especially in streams. That callback quite often synchronously calls the `emit` method. The `emit` method will also intentionally re-throw errors if there are no handlers. This is done because crashing is better than silently swallowing errors.

[Alex Early](https://github.com/aearly) explains this well: https://github.com/caolan/async/issues/1458#issuecomment-318182668

For most of your cases I suggest something like the following.

```javascript
if (err) {
   return callback(new PluginError(PLUGIN_NAME, err));
}

var e, result;

try {
   result = processSomething();
} catch (err) {
   e = new PluginError(PLUGIN_NAME, err);
}

callback(e, result);
```

**Comment by crissdev** [comment]
Thanks @CodeMan99
