### ISSUE TITLE
gulp-remove-code does not work with cshtml files

### ISSUE THREAD

**Issue by lidvarko** [crissdev/gulp-remove-code#22]
If the file extension is cshtml, then the gulp-remove-code does not recognise the `<!--removeIf(production)-->` comment within the HTML section. This works fine if I rename the file to html. Please add support for cshtml file format that may contain both html and c# code (`<!-- -->` or `//` as comment)

**Comment by lidvarko** [comment]
I can confirm that it is now working :-) Thanx!

**Comment by crissdev** [comment]
@lidvarko thanks
