### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mfeckie** [crissdev/gulp-remove-code#4]
Would you be interested in adding an additional use syntax?

The proposal, a tag like `<-- keepIf(production) -->` or `<-- removeUnless(production) -->`

The block  describes what should stay, rather than go, which makes the example below a very clear view of what you're using in dev vs production.

``` html
<!-- keepIf(development) -->
  <script src="vendor/jquery-2.1.4.js"></script>
<!-- endKeepIf(development) -->

<!-- keepIf(production) -->
  <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="/js/main.js"></script>
<!-- endKeepIf(production) -->
```

Happy to do some work on it if you're interested.

**Comment by crissdev** [comment]
@mfeckie Interesting...When I came across such situation I added a key that negates the original condition. But using `keepIf` / `removeUnless` makes more sense and I would be happy to have that feature.

Thanks.

**Comment by mckravchyk** [comment]
Try this: (requires gulp-replace)

```
p = p.pipe(replace('endKeepIf(', "endRemoveIf(!"));
p = p.pipe(replace('keepIf(', "removeIf(!"));

p = p.pipe(removeCode({ 'something': true }));
```

Then you can add a custom keepIf statement which will be replaced with removeIf negated statement.
