### ISSUE TITLE
UTF incompatibility?

### ISSUE THREAD

**Issue by JanVerkoyen** [crissdev/gulp-remove-code#6]
Running into problems with UTF characters like â, curly quotes, ...

**Comment by crissdev** [comment]
@JanVerkoyen can you provide a failing test case please? Thanks.

**Comment by JanVerkoyen** [comment]
Try this for example: [Codepen.io](http://codepen.io/JanVerkoyen/pen/zrLpyE)
Results in something like this:

> <h1>ÔÇ£Vendre son ├ómeÔÇØ</h1>

**Comment by crissdev** [comment]
@JanVerkoyen No problem. It's good you found the root cause.
