### ISSUE TITLE
Code is not removed from files with .scss file extension

### ISSUE THREAD

**Issue by edtalmadge** [crissdev/gulp-remove-code#7]
I'm trying to remove code from my Sass files (.scss), but can't seem to get it working.

I'm trying this in my gulp file:

`.pipe(removeCode({ responsive: false, commentStart: '/*', commentEnd: '*/' }))`

... And this in my .scss file

`/*removeIf(responsive)*/
.helloWorld { color: red; }
/*endRemoveIf(responsive)*/`

Is there a way to make it work?

**Comment by crissdev** [comment]
From the docs:

> The truthy values will remove the code

This means you must set `responsive` to true.
