### ISSUE TITLE
Returned stream cannot be paused with large number of files.

### ISSUE THREAD

**Issue by CodeMan99** [crissdev/gulp-remove-code#9]
Trying to use [combined-stream](https://github.com/felixge/node-combined-stream) directly after _gulp-remove-code_, but when I do my gulp task fails silently.

If I put another heavy io task after _gulp-remove-code_ like [gulp-debug](https://github.com/sindresorhus/gulp-debug) and before [`combinedStream.append`](https://github.com/felixge/node-combined-stream#combinedstreamappendstream), everything works as expected.

Failing Example (untested):

```javascript
var gulp = require('gulp');
var removeCode = require('gulp-remove-code');
var combine = require('combined-stream');

gulp.task('default', function(callback) {
    var s = gulp.src('**/*.js'); // say, 70 or so js files with 500 average lines of code
    var h = gulp.src('**/*.html');
    var c = combine.create();

    s = s.pipe(removeCode({umd: true}));

    c.append(s); // the "s" stream is paused, but removeCode is still processing files
    c.append(h);

    c = c.pipe(gulp.dest('out'));

    c.on('end', callback);
});
```

**Comment by crissdev** [comment]
@CodeMan99 I can't reproduce this using the below test case. When stream is paused the plugin does not process any files. _I'm using the `refactor` branch._

```js
it('should pause stream created by gulp-remove-code', done => {
  let cs = require('combined-stream').create();
  let gs = require('gulp').src('node_modules/**/*.js');

  gs.pause();
  assert.strictEqual(gs._readableState.flowing, false);
  done();

  // gs = gs.pipe(removeCode({_deadbeef: true}));
  // cs.append(gs);
  //
  // cs = cs.pipe(require('gulp').dest('./out'));
  // cs.on('end', done);
});
```

**Comment by CodeMan99** [comment]
Yeah, probably so. This was a bit too long ago.

Closing as I did find a work around and it may be a non-issue anyway.
